version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
    overwrite: true
# hooks:
#   ApplicationStart:
#     - location: start.sh
#       timeout: 180
hooks:
  BeforeInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
